# Generated by Django 3.0.8 on 2020-07-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200726_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='documento',
            new_name='doc_identificacao',
        ),
    ]
